# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: https://RTM945.github.io/
title: rtmsoft
author: rtm
description: Personal blog
avatar: 8003484.jpg
email: rtmsoft1@gmail.com
github: RTM945 # username
twitter: rtmsoft1
linkedin: #username
stackoverflow: #username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: #username
google_analytics: #UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
